const {test}=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const vm=require('node:vm');
const I=require('../assets/intelligence-core.js');
const {queueFor,collectStore}=require('../scripts/naver-evidence-check.cjs');
const now=Date.parse('2026-09-17T12:00:00+09:00');
const s={id:'fixture-1',name:'세왕주막',addr:'서울특별시 강남구 테헤란로 12, 2층 201호',permitDate:'20260915',type:'ilban',typeLabel:'일반음식점',upte:'기타'};
const place={title:'<b>세왕주막</b>',roadAddress:'서울 강남구 테헤란로 12 2층 201호',category:'음식점>한식주점',link:'https://example.com/place'};
test('exact name and building/floor/unit produce evidence, not a probability',()=>{const m=I.match(s,[place]);assert.equal(m.status,'matched');assert.equal(m.found,true);assert.equal(m.score,100);assert.ok(m.reasons.includes('호수 일치'));});
test('same name in another city is not matched',()=>{assert.equal(I.match(s,[{...place,roadAddress:'부산광역시 해운대구 해운대로 12 201호'}]).status,'candidate');});
test('same building with different unit is not matched',()=>{const m=I.match(s,[{...place,roadAddress:'서울 강남구 테헤란로 12 2층 202호'}]);assert.equal(m.status,'candidate');assert.ok(m.candidates[0].conflicts.includes('호수 불일치'));});
test('basement and upper floor differ',()=>{assert.equal(I.match({...s,addr:'서울 강남구 테헤란로 12 지하1층'},[{...place,roadAddress:'서울 강남구 테헤란로 12 1층'}]).status,'candidate');});
test('two similar candidates require review',()=>{const st={...s,addr:'서울 강남구 테헤란로 12'};const m=I.match(st,[place,{...place,title:'세왕주막 강남점',roadAddress:'서울 강남구 테헤란로 12 3층 301호'}]);assert.equal(m.status,'ambiguous');});
test('empty or short name cannot accidentally match every result',()=>{assert.equal(I.match({...s,name:''},[place]).status,'candidate');assert.equal(I.match({...s,name:'세'},[place]).status,'candidate');});
test('search errors are never unregistered',()=>{const m=I.match(s,[],true);assert.equal(m.status,'error');assert.equal(m.found,null);assert.equal(I.isUnresolved(m),false);});
test('zero results preserve uncertainty about opening',()=>{const m=I.match(s,[]);assert.equal(m.status,'no_result');assert.match(m.reasons[0],/확정 아님/);});
test('legacy registered cache needs revalidation',()=>{assert.equal(I.state({nstat:'registered',found:true}),'legacy');});
test('place category only contributes after a reliable match',()=>{const e=I.match(s,[place]);assert.equal(I.classify({...s,name:'가정식당'},e).basis,'장소 분류 기반 추정');assert.equal(I.classify({...s,name:'가정식당'},{...e,status:'candidate'}).label,'음식점·세부업태 미확인');});
test('closed permits never receive sales priority',()=>{assert.equal(I.lead({...s,closedDate:'20260916'},null,{},now).score,0);});
test('human closed/cafe corrections change sales priority',()=>{assert.equal(I.lead(s,null,{opening:'closed'},now).score,0);assert.equal(I.classify(s,null,{actualCategory:'카페·디저트'}).points,3);});
test('unknown search gets no speculative opening bonus',()=>{assert.equal(I.lead(s,I.match(s,[]),{},now).score,I.lead(s,I.match(s,[place]),{},now).score);});
test('recheck schedule includes day 3',()=>{const checked=I.date(s.permitDate)+3600000;const due=I.nextCheck(s,{...I.match(s,[]),checked_at:new Date(checked).toISOString()},now);assert.equal(due,I.date(s.permitDate)+3*I.DAY);});
test('legacy locked registrations do not stay locked forever',()=>{const c={nstat:'registered',locked:true,checked_at:'2026-08-01T00:00:00Z'};assert.equal(queueFor([s],{[s.id]:c},now).length,1);});
test('future and very old permits do not get cron calls',()=>{assert.equal(I.nextCheck({...s,permitDate:'20270101'},null,now),null);assert.equal(I.nextCheck({...s,permitDate:'20250101'},null,now),null);});
test('nightly and interactive matching use the same engine',async()=>{const result=await collectStore(s,async()=>({items:[place]}));assert.equal(result.status,I.match(s,[place]).status);assert.equal(result.version,I.VERSION);});
test('nightly incomplete search propagates error',async()=>{await assert.rejects(collectStore(s,async()=>{throw new Error('http_429');}),/429/);});
test('duplicate permits do not inflate brand growth',()=>{const m=I.brandMetrics([s,s],now);assert.equal(m.current90,1);assert.equal(m.change,null);});
test('first observed regional sequence is not a prediction',()=>{const base={name:'가상브랜드',status:'영업'};const m=I.brandMetrics([{...base,id:'a',addr:'부산광역시',permitDate:'20260601'},{...base,id:'b',addr:'대구광역시',permitDate:'20260610'},{...base,id:'c',addr:'경기도',permitDate:'20260810'}],now);assert.equal(m.signal,'지방 다지역 → 수도권 진입 관측');});
test('closures without dates are not silently counted as current',()=>{assert.equal(I.brandMetrics([{...s,closed:true}],now).closed90,0);});
test('HTML inline scripts parse after integration',()=>{const html=fs.readFileSync('index.html','utf8');for(const m of html.matchAll(/<script\b[^>]*>([\s\S]*?)<\/script>/gi)){new vm.Script(m[1]);}assert.match(html,/class="auth-pending"/);assert.match(html,/mountIntelligence/);});
test('new client modules parse and do not expose API credentials',()=>{for(const f of ['assets/intelligence-core.js','assets/intelligence-ui.js']){const code=fs.readFileSync(f,'utf8');new vm.Script(code);assert.doesNotMatch(code,/NAVER_CLIENT_SECRET|GOOGLE_API_KEY/);}});
